# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡

  Thank you and congratsğŸ‰ for opening your very first issue in this project. Please make sure to go through our [Code of Conduct](https://github.com/himanshusharma89/relic_bazaar/blob/master/CODE_OF_CONDUCT.md)
  and [contributing](https://github.com/himanshusharma89/relic_bazaar/blob/master/CONTRIBUTING.md) files and also please wait till you  are assigned an issue to start working on it.ğŸ˜Š

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–

  Thank you and congratsğŸ‰ for opening your first pull request. Please make sure you have gone through our [Code of Conduct](https://github.com/himanshusharma89/relic_bazaar/blob/master/CODE_OF_CONDUCT.md)
  and [contributing](https://github.com/himanshusharma89/relic_bazaar/blob/master/CONTRIBUTING.md) files before making this pr. ğŸ™ŒğŸ™Œ We will get back to you as soon as we can ğŸ˜„.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
