name: relic_bazaar
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.8
  flutter_html: ^2.1.2
  firebase_remote_config: ^0.11.0
  firebase_core: any
  google_fonts: ^2.1.0
  razorpay_flutter: ^1.2.7
  google_mobile_ads: ^0.13.4
  geolocator: ^7.6.2
  geocoder: ^0.2.1
  flutter_svg: ^0.22.0
  provider:
  advance_pdf_viewer: any
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.1
  webview_flutter: ^2.1.0
  cloud_firestore: ^2.5.3
  modal_progress_hud: ^0.1.3
  carousel_slider: ^4.0.0
  http: any
  image_picker: any
  firebase_storage: ^10.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/items/

  fonts:
    - family: RelicIcons
      fonts:
        - asset: assets/icon/RelicIcons.ttf
    - family: Pixer
      fonts:
        - asset: assets/fonts/pixer.ttf
